# Spring configuration
spring:
  datasource:
    url: jdbc:mysql://vps817240.ovh.net:3306/team3_schema?serverTimezone=UTC
    username: team3
    password: 70JDogNy
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update # auto create or update database schema
    database: mysql

# Logger
logging:
  level:
    root: INFO
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO