# Spring configuration
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/VehiclesRental?serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update # auto create or update database schema
    database: mysql

# Logger
logging:
  level:
    root: INFO
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO